/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chat;

import java.awt.Color;

/**
 *
 * @author Admin
 */
public class ChatWindow extends javax.swing.JFrame {

    /**
     * Creates new form ChatWindow
     */
    public ChatWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFrame = new javax.swing.JPanel();
        separator = new javax.swing.JSeparator();
        messageArea = new javax.swing.JPanel();
        typingAreaFrame = new javax.swing.JScrollPane();
        typingArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        separator2 = new javax.swing.JSeparator();
        chatAreaFrame = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(23, 33, 43));
        setResizable(false);

        mainFrame.setBackground(new java.awt.Color(14, 22, 33));
        mainFrame.setForeground(new java.awt.Color(14, 22, 33));
        mainFrame.setAutoscrolls(true);

        separator.setBackground(new java.awt.Color(90, 100, 113));
        separator.setForeground(new java.awt.Color(90, 100, 113));

        messageArea.setBackground(new java.awt.Color(14, 22, 33));
        messageArea.setForeground(new java.awt.Color(14, 22, 33));

        typingAreaFrame.setBackground(new java.awt.Color(23, 33, 43));
        typingAreaFrame.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(90, 100, 113), 1, true));
        typingAreaFrame.setOpaque(false);

        typingArea.setBackground(new java.awt.Color(23, 33, 43));
        typingArea.setColumns(20);
        typingArea.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        typingArea.setForeground(new java.awt.Color(255, 255, 255));
        typingArea.setLineWrap(true);
        typingArea.setRows(3);
        typingArea.setToolTipText("");
        typingArea.setWrapStyleWord(true);
        typingArea.setBorder(null);
        typingArea.setCaretColor(new java.awt.Color(90, 100, 113));
        typingArea.setDisabledTextColor(new java.awt.Color(90, 100, 113));
        typingArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                typingAreaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                typingAreaFocusLost(evt);
            }
        });
        typingAreaFrame.setViewportView(typingArea);

        sendButton.setBackground(new java.awt.Color(23, 33, 43));
        sendButton.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        sendButton.setForeground(new java.awt.Color(90, 100, 113));
        sendButton.setText("Отправить!");
        sendButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(90, 100, 113), 1, true));
        sendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendButtonMouseClicked(evt);
            }
        });

        separator2.setBackground(new java.awt.Color(90, 100, 113));
        separator2.setForeground(new java.awt.Color(90, 100, 113));
        separator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout messageAreaLayout = new javax.swing.GroupLayout(messageArea);
        messageArea.setLayout(messageAreaLayout);
        messageAreaLayout.setHorizontalGroup(
            messageAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(typingAreaFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        messageAreaLayout.setVerticalGroup(
            messageAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messageAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(typingAreaFrame)
                    .addComponent(separator2)
                    .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        chatAreaFrame.setBackground(new java.awt.Color(14, 22, 33));
        chatAreaFrame.setBorder(null);
        chatAreaFrame.setAutoscrolls(true);

        chatArea.setBackground(new java.awt.Color(14, 22, 33));

        javax.swing.GroupLayout chatAreaLayout = new javax.swing.GroupLayout(chatArea);
        chatArea.setLayout(chatAreaLayout);
        chatAreaLayout.setHorizontalGroup(
            chatAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );
        chatAreaLayout.setVerticalGroup(
            chatAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        chatAreaFrame.setViewportView(chatArea);

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame);
        mainFrame.setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator)
            .addComponent(messageArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chatAreaFrame, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainFrameLayout.createSequentialGroup()
                .addComponent(chatAreaFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(messageArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typingAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_typingAreaFocusGained
        if(typingArea.getText().equals("Введите сообщение...")) {
            typingArea.setText("");
            typingArea.setForeground(new Color(90,100,113));
        }
    }//GEN-LAST:event_typingAreaFocusGained

    private void typingAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_typingAreaFocusLost
        if(typingArea.getText().equals("")) {
            typingArea.setText("Введите сообщение...");
            typingArea.setForeground(new Color(90,100,113));
        }
    }//GEN-LAST:event_typingAreaFocusLost

    private void sendButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendButtonMouseClicked
        String message = typingArea.getText();
        jLabel1 = new javax.swing.JLabel();
    }//GEN-LAST:event_sendButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chatArea;
    private javax.swing.JScrollPane chatAreaFrame;
    private javax.swing.JPanel mainFrame;
    private javax.swing.JPanel messageArea;
    private javax.swing.JButton sendButton;
    private javax.swing.JSeparator separator;
    private javax.swing.JSeparator separator2;
    private javax.swing.JTextArea typingArea;
    private javax.swing.JScrollPane typingAreaFrame;
    // End of variables declaration//GEN-END:variables
}
