/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chat;

import java.awt.Color;
import javax.swing.DefaultListModel;

/**
 *
 * @author Admin
 */
public class ChatWindow extends javax.swing.JFrame {

    /**
     * Creates new form ChatWindow
     */
    public ChatWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomePane = new javax.swing.JPanel();
        nicknameField = new javax.swing.JTextField();
        nicknameLabel = new javax.swing.JLabel();
        sendNickname = new javax.swing.JButton();
        welcomeWarningText = new javax.swing.JLabel();
        welcomeWarningText.setVisible(false);
        mainFrame = new javax.swing.JPanel();
        separator = new javax.swing.JSeparator();
        chatAreaFrame = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JList<>();
        messageArea = new javax.swing.JPanel();
        typingAreaFrame = new javax.swing.JScrollPane();
        typingArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        separator2 = new javax.swing.JSeparator();
        messageWarningText = new javax.swing.JLabel();
        messageWarningText.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(23, 33, 43));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomePane.setBackground(new java.awt.Color(14, 22, 33));

        nicknameField.setBackground(new java.awt.Color(23, 33, 43));
        nicknameField.setForeground(new java.awt.Color(255, 255, 255));
        nicknameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(90, 100, 113), 1, true));

        nicknameLabel.setBackground(new java.awt.Color(14, 22, 33));
        nicknameLabel.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        nicknameLabel.setForeground(new java.awt.Color(90, 100, 113));
        nicknameLabel.setText("Ваше имя:");

        sendNickname.setBackground(new java.awt.Color(90, 100, 113));
        sendNickname.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        sendNickname.setForeground(new java.awt.Color(14, 22, 33));
        sendNickname.setText("Войти");
        sendNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendNicknameActionPerformed(evt);
            }
        });

        welcomeWarningText.setForeground(new java.awt.Color(255, 0, 0));
        welcomeWarningText.setText("Введите имя (до 20 символов)");
        welcomeWarningText.setFocusable(false);

        javax.swing.GroupLayout welcomePaneLayout = new javax.swing.GroupLayout(welcomePane);
        welcomePane.setLayout(welcomePaneLayout);
        welcomePaneLayout.setHorizontalGroup(
            welcomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePaneLayout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addGroup(welcomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePaneLayout.createSequentialGroup()
                        .addComponent(nicknameField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePaneLayout.createSequentialGroup()
                        .addComponent(welcomeWarningText, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))))
            .addGroup(welcomePaneLayout.createSequentialGroup()
                .addGroup(welcomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(welcomePaneLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(nicknameLabel))
                    .addGroup(welcomePaneLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(sendNickname)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        welcomePaneLayout.setVerticalGroup(
            welcomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePaneLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(nicknameLabel)
                .addGap(30, 30, 30)
                .addComponent(nicknameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeWarningText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendNickname)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        getContentPane().add(welcomePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 470));

        mainFrame.setBackground(new java.awt.Color(14, 22, 33));
        mainFrame.setForeground(new java.awt.Color(14, 22, 33));
        mainFrame.setAutoscrolls(true);

        separator.setBackground(new java.awt.Color(90, 100, 113));
        separator.setForeground(new java.awt.Color(90, 100, 113));

        chatAreaFrame.setBackground(new java.awt.Color(14, 22, 33));
        chatAreaFrame.setBorder(null);
        chatAreaFrame.setAutoscrolls(true);

        chatArea.setBackground(new java.awt.Color(14, 22, 33));
        chatArea.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        chatArea.setForeground(new java.awt.Color(255, 255, 255));
        chatAreaFrame.setViewportView(chatArea);

        messageArea.setBackground(new java.awt.Color(14, 22, 33));
        messageArea.setForeground(new java.awt.Color(14, 22, 33));

        typingAreaFrame.setBackground(new java.awt.Color(23, 33, 43));
        typingAreaFrame.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(90, 100, 113), 1, true));
        typingAreaFrame.setOpaque(false);

        typingArea.setBackground(new java.awt.Color(23, 33, 43));
        typingArea.setColumns(20);
        typingArea.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        typingArea.setForeground(new java.awt.Color(255, 255, 255));
        typingArea.setLineWrap(true);
        typingArea.setRows(3);
        typingArea.setToolTipText("");
        typingArea.setWrapStyleWord(true);
        typingArea.setBorder(null);
        typingArea.setCaretColor(new java.awt.Color(90, 100, 113));
        typingArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        typingArea.setDisabledTextColor(new java.awt.Color(90, 100, 113));
        typingAreaFrame.setViewportView(typingArea);

        sendButton.setBackground(new java.awt.Color(23, 33, 43));
        sendButton.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        sendButton.setForeground(new java.awt.Color(90, 100, 113));
        sendButton.setText("Отправить!");
        sendButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(90, 100, 113), 1, true));
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        separator2.setBackground(new java.awt.Color(90, 100, 113));
        separator2.setForeground(new java.awt.Color(90, 100, 113));
        separator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        messageWarningText.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        messageWarningText.setForeground(new java.awt.Color(255, 0, 0));
        messageWarningText.setText("Введите сообщение. До 60 символов");

        javax.swing.GroupLayout messageAreaLayout = new javax.swing.GroupLayout(messageArea);
        messageArea.setLayout(messageAreaLayout);
        messageAreaLayout.setHorizontalGroup(
            messageAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messageAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(messageAreaLayout.createSequentialGroup()
                        .addComponent(typingAreaFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(messageAreaLayout.createSequentialGroup()
                        .addComponent(messageWarningText)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        messageAreaLayout.setVerticalGroup(
            messageAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messageAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(typingAreaFrame)
                    .addComponent(separator2)
                    .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(messageWarningText)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame);
        mainFrame.setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainFrameLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(chatAreaFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainFrameLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainFrameLayout.createSequentialGroup()
                    .addComponent(chatAreaFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 104, Short.MAX_VALUE)))
        );

        getContentPane().add(mainFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   DefaultListModel model = new DefaultListModel();
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String message = typingArea.getText();
        chatArea.setModel(model);
        if(message.isEmpty() || message.length()>60) {
            messageWarningText.setVisible(true);
        } else {
            model.addElement(message + name); 
            messageWarningText.setVisible(false);
        }
        
    }//GEN-LAST:event_sendButtonActionPerformed
    String name;
    private void sendNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendNicknameActionPerformed
        String nickname = nicknameField.getText();
        if (nickname.isEmpty() || nickname.length()>20) {
            welcomeWarningText.setVisible(true);
        } else {
            name = nicknameField.getText();
            welcomePane.setVisible(false);
        }
    }//GEN-LAST:event_sendNicknameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> chatArea;
    private javax.swing.JScrollPane chatAreaFrame;
    private javax.swing.JPanel mainFrame;
    private javax.swing.JPanel messageArea;
    private javax.swing.JLabel messageWarningText;
    private javax.swing.JTextField nicknameField;
    private javax.swing.JLabel nicknameLabel;
    private javax.swing.JButton sendButton;
    private javax.swing.JButton sendNickname;
    private javax.swing.JSeparator separator;
    private javax.swing.JSeparator separator2;
    private javax.swing.JTextArea typingArea;
    private javax.swing.JScrollPane typingAreaFrame;
    private javax.swing.JPanel welcomePane;
    private javax.swing.JLabel welcomeWarningText;
    // End of variables declaration//GEN-END:variables
}
