/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chat;

import java.awt.Color;
import javax.swing.DefaultListModel;

/**
 *
 * @author Admin
 */
public class ChatWindow extends javax.swing.JFrame {

    /**
     * Creates new form ChatWindow
     */
    public ChatWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFrame = new javax.swing.JPanel();
        separator = new javax.swing.JSeparator();
        messageArea = new javax.swing.JPanel();
        typingAreaFrame = new javax.swing.JScrollPane();
        typingArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        separator2 = new javax.swing.JSeparator();
        chatAreaFrame = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JList<>();
        welcomePane = new javax.swing.JPanel();
        nicknameField = new javax.swing.JTextField();
        nicknameLabel = new javax.swing.JLabel();
        sendNickname = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(23, 33, 43));
        setResizable(false);

        mainFrame.setBackground(new java.awt.Color(14, 22, 33));
        mainFrame.setForeground(new java.awt.Color(14, 22, 33));
        mainFrame.setAutoscrolls(true);

        separator.setBackground(new java.awt.Color(90, 100, 113));
        separator.setForeground(new java.awt.Color(90, 100, 113));

        messageArea.setBackground(new java.awt.Color(14, 22, 33));
        messageArea.setForeground(new java.awt.Color(14, 22, 33));

        typingAreaFrame.setBackground(new java.awt.Color(23, 33, 43));
        typingAreaFrame.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(90, 100, 113), 1, true));
        typingAreaFrame.setOpaque(false);

        typingArea.setBackground(new java.awt.Color(23, 33, 43));
        typingArea.setColumns(20);
        typingArea.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        typingArea.setForeground(new java.awt.Color(255, 255, 255));
        typingArea.setLineWrap(true);
        typingArea.setRows(3);
        typingArea.setToolTipText("");
        typingArea.setWrapStyleWord(true);
        typingArea.setBorder(null);
        typingArea.setCaretColor(new java.awt.Color(90, 100, 113));
        typingArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        typingArea.setDisabledTextColor(new java.awt.Color(90, 100, 113));
        typingArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                typingAreaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                typingAreaFocusLost(evt);
            }
        });
        typingAreaFrame.setViewportView(typingArea);

        sendButton.setBackground(new java.awt.Color(23, 33, 43));
        sendButton.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        sendButton.setForeground(new java.awt.Color(90, 100, 113));
        sendButton.setText("Отправить!");
        sendButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(90, 100, 113), 1, true));
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        separator2.setBackground(new java.awt.Color(90, 100, 113));
        separator2.setForeground(new java.awt.Color(90, 100, 113));
        separator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout messageAreaLayout = new javax.swing.GroupLayout(messageArea);
        messageArea.setLayout(messageAreaLayout);
        messageAreaLayout.setHorizontalGroup(
            messageAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(typingAreaFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        messageAreaLayout.setVerticalGroup(
            messageAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messageAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(typingAreaFrame)
                    .addComponent(separator2)
                    .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        chatAreaFrame.setBackground(new java.awt.Color(14, 22, 33));
        chatAreaFrame.setBorder(null);
        chatAreaFrame.setAutoscrolls(true);

        chatArea.setBackground(new java.awt.Color(14, 22, 33));
        chatArea.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        chatArea.setForeground(new java.awt.Color(255, 255, 255));
        chatAreaFrame.setViewportView(chatArea);

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame);
        mainFrame.setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator)
            .addComponent(messageArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chatAreaFrame, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainFrameLayout.createSequentialGroup()
                .addComponent(chatAreaFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(messageArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        welcomePane.setBackground(new java.awt.Color(14, 22, 33));

        nicknameField.setBackground(new java.awt.Color(23, 33, 43));
        nicknameField.setForeground(new java.awt.Color(255, 255, 255));
        nicknameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(90, 100, 113), 1, true));

        nicknameLabel.setBackground(new java.awt.Color(14, 22, 33));
        nicknameLabel.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        nicknameLabel.setForeground(new java.awt.Color(90, 100, 113));
        nicknameLabel.setText("Ваше имя:");

        sendNickname.setBackground(new java.awt.Color(90, 100, 113));
        sendNickname.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        sendNickname.setForeground(new java.awt.Color(14, 22, 33));
        sendNickname.setText("Войти");
        sendNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendNicknameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout welcomePaneLayout = new javax.swing.GroupLayout(welcomePane);
        welcomePane.setLayout(welcomePaneLayout);
        welcomePaneLayout.setHorizontalGroup(
            welcomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePaneLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(nicknameField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sendNickname)
                .addGap(197, 197, 197))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nicknameLabel)
                .addGap(199, 199, 199))
        );
        welcomePaneLayout.setVerticalGroup(
            welcomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePaneLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(nicknameLabel)
                .addGap(18, 18, 18)
                .addComponent(nicknameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(sendNickname)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(welcomePane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(welcomePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typingAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_typingAreaFocusGained
        if(typingArea.getText().equals("Введите сообщение...")) {
            typingArea.setText("");
            typingArea.setForeground(new Color(90,100,113));
        }
    }//GEN-LAST:event_typingAreaFocusGained

    private void typingAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_typingAreaFocusLost
        if(typingArea.getText().equals("")) {
            typingArea.setText("Введите сообщение...");
            typingArea.setForeground(new Color(90,100,113));
        }
    }//GEN-LAST:event_typingAreaFocusLost

   DefaultListModel model = new DefaultListModel();
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String message = typingArea.getText().trim();
        chatArea.setModel(model);
        model.addElement(message + "\nАфрика");
    }//GEN-LAST:event_sendButtonActionPerformed

    private void sendNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendNicknameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> chatArea;
    private javax.swing.JScrollPane chatAreaFrame;
    private javax.swing.JPanel mainFrame;
    private javax.swing.JPanel messageArea;
    private javax.swing.JTextField nicknameField;
    private javax.swing.JLabel nicknameLabel;
    private javax.swing.JButton sendButton;
    private javax.swing.JButton sendNickname;
    private javax.swing.JSeparator separator;
    private javax.swing.JSeparator separator2;
    private javax.swing.JTextArea typingArea;
    private javax.swing.JScrollPane typingAreaFrame;
    private javax.swing.JPanel welcomePane;
    // End of variables declaration//GEN-END:variables
}
